title: CV 
description:  A beautiful template for your CV.
url: https://jekyll-cv.stavrospanakakis.com
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml

lang: "fr"
css_theme: "custom"

use_months: True
use_short_months: True
show_degree_title: False

exclude_jobs: ["paniers", "Vietnam"]